### ISSUE TITLE
Last silence not cut

### ISSUE THREAD

**Issue by markouustalu** [DarkTrick/python-video-silence-cutter#10]
It would seem that if the video ends with a silence, that is not left out.

btw, really helpful piece of code, thank you for putting it together.

**Comment by DarkTrick** [comment]
@markouustalu 
Can you provide some test file? I added a testfile `testdata/silence_in_the_end.mkv`, which seems to run flawlessly.

Feel free to reopen the issue, if you can provide an example :)

**Comment by markouustalu** [comment]
Sorry, did not have time. Did you find a bug?

Marko

**Comment by DarkTrick** [comment]
> Sorry, did not have time. Did you find a bug?
I didn't look deeper into it, but the one test file I created (see files in repository) worked fine as far as I can say.

**Comment by markouustalu** [comment]
indeed, i cannot reproduce it anymore. must have been my own mistake

**Comment by DarkTrick** [comment]
Possibly it only happens on certain occasions. In case you hit the problem again, I'd appreciate hearing from you again! 👍️
